/** ****************************************************************************
 * @brief Internal state machine events generated by Codec.
 */

#ifndef FKMG_CODEC_SM_EVT_H
#define FKMG_CODEC_SM_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "../id.h"
#include "../instance_cfg.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum Codec_SM_Evt_Sig{
    k_Codec_SM_Evt_Sig_Beg,                           // Inclusive
    k_Codec_SM_Evt_Sig_Min = k_Codec_SM_Evt_Sig_Beg,    // Inclusive
    k_Codec_SM_Evt_Sig_1st = k_Codec_SM_Evt_Sig_Beg,    // Inclusive

	k_Codec_SM_Evt_Sig_Init_Instance = k_Codec_SM_Evt_Sig_Beg,
    #if CONFIG_FKMG_CODEC_ALLOW_SHUTDOWN
	k_Codec_SM_Evt_Sig_Deinit_Instance,
    #endif
	k_Codec_SM_Evt_Sig_XXX,

    k_Codec_SM_Evt_Sig_End,                           // Exclusive
    k_Codec_SM_Evt_Sig_Max = k_Codec_SM_Evt_Sig_End - 1,// Inclusive
    k_Codec_SM_Evt_Sig_Lst = k_Codec_SM_Evt_Sig_End - 1,// Inclusive
    k_Codec_SM_Evt_Sig_Cnt = k_Codec_SM_Evt_Sig_End
                         - k_Codec_SM_Evt_Sig_Beg,	// Inclusive
	k_Codec_SM_Evt_Sig_Ivd = k_Codec_SM_Evt_Sig_End
};

/* Data signal k_Codec_SM_Evt_Sig_Init_Instance can generate. */
struct Codec_SM_Evt_Sig_Init_Instance{
    struct Codec_Instance_Cfg cfg;
};

/* Data signal k_Codec_SM_Sig_XXX can generate. */
struct Codec_SM_Evt_Sig_Convert{
    enum Codec_Id id;
};

struct Codec_SM_Evt_Sig_Force_Change{
    enum Codec_Id id;
};


/* Events (i.e. signal + signal's data if any) Codec State Machine generates. */
struct Codec_SM_Evt{
	enum Codec_SM_Evt_Sig sig;
	union Codec_SM_Evt_Data{
        struct Codec_SM_Evt_Sig_Init_Instance  init_inst;
        struct Codec_SM_Evt_Sig_Convert        convert;
        struct Codec_SM_Evt_Sig_Force_Change   force_change;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_CODEC_SM_EVT_H */
