/** ****************************************************************************
 * @brief Events generated by Voice module.
 *
 * The public events Voice module generates.
 */

#ifndef FKMG_VOICE_EVT_H
#define FKMG_VOICE_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "id.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum Voice_Evt_Sig{
    k_Voice_Evt_Sig_Beg,                        // Inclusive
    k_Voice_Evt_Sig_Min = k_Voice_Evt_Sig_Beg,    // Inclusive
    k_Voice_Evt_Sig_1st = k_Voice_Evt_Sig_Beg,    // Inclusive

    k_Voice_Evt_Sig_Instance_Initialized = k_Voice_Evt_Sig_Beg,
    #if CONFIG_FKMG_VOICE_SHUTDOWN_ENABLED
    k_Voice_Evt_Sig_Instance_Deinitialized,
    #endif
    k_Voice_Evt_Sig_Changed, // Value changed
    k_Voice_Evt_Sig_Write_Ready,
    k_Voice_Evt_Sig_RX_Ready,

    k_Voice_Evt_Sig_End,                        // Exclusive
    k_Voice_Evt_Sig_Max = k_Voice_Evt_Sig_End - 1,// Inclusive
    k_Voice_Evt_Sig_Lst = k_Voice_Evt_Sig_End - 1,// Inclusive
    k_Voice_Evt_Sig_Cnt = k_Voice_Evt_Sig_End
                      - k_Voice_Evt_Sig_Beg,	  // Inclusive
	k_Voice_Evt_Sig_Ivd = k_Voice_Evt_Sig_End
};

/* Forward references to prevent include interdependent items getting declared
 * out-of-order. */
struct Voice_Instance;

/* Data signal k_Voice_Evt_Sig_Instance_Initialized can generate. */
struct Voice_Evt_Data_Instance_Initialized{
    struct Voice_Instance * p_inst;
};

/* Data signal k_Voice_Evt_Sig_Write_Ready can generate. */
struct Voice_Evt_Data_Write_Voice{
    enum Voice_Id id;
    uint8_t Voice_status; 
    uint8_t ctrl_byte;
    bool seq;
    uint8_t step;
    uint8_t offset;
};

/* Data signal k_Voice_Evt_Sig_Changed can generate. */
struct Voice_Evt_Data_Changed{
    bool seq;
    uint8_t stp; 
    uint16_t val; 
};

/* Data signal k_Voice_Evt_Sig_RX_Ready can generate. */
struct Voice_Evt_Voice_RX_Ready{
    uint8_t bytes[3]; 
};

/* Events (i.e. signal + signal's data if any) that can be generated. */
struct Voice_Evt{
	enum Voice_Evt_Sig sig;
	union Voice_Evt_Data{
        struct Voice_Evt_Data_Instance_Initialized   initd;
        struct Voice_Evt_Data_Write_Voice             Voice_write;
        struct Voice_Evt_Voice_RX_Ready               Voice_command;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_VOICE_EVT_H */
