/** ****************************************************************************
 * @brief Internal state machine events generated by MIDI.
 */

#ifndef FKMG_MIDI_SM_EVT_H
#define FKMG_MIDI_SM_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "../id.h"
#include "../instance_cfg.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum MIDI_SM_Evt_Sig{
    k_MIDI_SM_Evt_Sig_Beg,                           // Inclusive
    k_MIDI_SM_Evt_Sig_Min = k_MIDI_SM_Evt_Sig_Beg,    // Inclusive
    k_MIDI_SM_Evt_Sig_1st = k_MIDI_SM_Evt_Sig_Beg,    // Inclusive

	k_MIDI_SM_Evt_Sig_Init_Instance = k_MIDI_SM_Evt_Sig_Beg,
    #if CONFIG_FKMG_MIDI_ALLOW_SHUTDOWN
	k_MIDI_SM_Evt_Sig_Deinit_Instance,
    #endif
    k_MIDI_SM_Evt_Sig_Changed,
	k_MIDI_SM_Evt_Sig_Write_MIDI,
	k_MIDI_SM_Evt_Sig_Force_Change,

    k_MIDI_SM_Evt_Sig_End,                           // Exclusive
    k_MIDI_SM_Evt_Sig_Max = k_MIDI_SM_Evt_Sig_End - 1,// Inclusive
    k_MIDI_SM_Evt_Sig_Lst = k_MIDI_SM_Evt_Sig_End - 1,// Inclusive
    k_MIDI_SM_Evt_Sig_Cnt = k_MIDI_SM_Evt_Sig_End
                         - k_MIDI_SM_Evt_Sig_Beg,	// Inclusive
	k_MIDI_SM_Evt_Sig_Ivd = k_MIDI_SM_Evt_Sig_End
};

/* Data signal k_MIDI_SM_Evt_Sig_Init_Instance can generate. */
struct MIDI_SM_Evt_Sig_Init_Instance{
    struct MIDI_Instance_Cfg cfg;
};

/* Data signal k_MIDI_SM_Sig_Write can generate. */
struct MIDI_SM_Evt_Sig_Write_MIDI{
    enum MIDI_Id id;
    uint8_t midi_status; 
    uint8_t ctrl_byte;
    bool seq;
    uint8_t step;
    uint8_t offset;
};

/* Data signal k_MIDI_SM_Sig_Changed can generate. */
struct MIDI_SM_Evt_Sig_Changed{
    bool seq;
    uint8_t stp;
    uint16_t val; 
};


/* Events (i.e. signal + signal's data if any) MIDI State Machine generates. */
struct MIDI_SM_Evt{
	enum MIDI_SM_Evt_Sig sig;
	union MIDI_SM_Evt_Data{
        struct MIDI_SM_Evt_Sig_Init_Instance    init_inst;
        struct MIDI_SM_Evt_Sig_Write_MIDI       midi_write;
        struct MIDI_SM_Evt_Sig_Changed          changed;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_MIDI_SM_EVT_H */
