/** ****************************************************************************
 * @brief Events generated by Sensor module.
 *
 * The public events Sensor module generates.
 */

#ifndef FKMG_SENSOR_EVT_H
#define FKMG_SENSOR_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "id.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum Sensor_Evt_Sig{
    k_Sensor_Evt_Sig_Beg,                        // Inclusive
    k_Sensor_Evt_Sig_Min = k_Sensor_Evt_Sig_Beg,    // Inclusive
    k_Sensor_Evt_Sig_1st = k_Sensor_Evt_Sig_Beg,    // Inclusive

    k_Sensor_Evt_Sig_Instance_Initialized = k_Sensor_Evt_Sig_Beg,
    #if CONFIG_FKMG_SENSOR_SHUTDOWN_ENABLED
    k_Sensor_Evt_Sig_Instance_Deinitialized,
    #endif
    k_Sensor_Evt_Sig_TimerUp,                    //
    k_Sensor_Evt_Sig_Read,                      // Write to Sensor
         

    k_Sensor_Evt_Sig_End,                        // Exclusive
    k_Sensor_Evt_Sig_Max = k_Sensor_Evt_Sig_End - 1,// Inclusive
    k_Sensor_Evt_Sig_Lst = k_Sensor_Evt_Sig_End - 1,// Inclusive
    k_Sensor_Evt_Sig_Cnt = k_Sensor_Evt_Sig_End
                      - k_Sensor_Evt_Sig_Beg,	  // Inclusive
	k_Sensor_Evt_Sig_Ivd = k_Sensor_Evt_Sig_End
};

/* Forward references to prevent include interdependent items getting declared
 * out-of-order. */
struct Sensor_Instance;

/* Data signal k_Sensor_Evt_Sig_Instance_Initialized can generate. */
struct Sensor_Evt_Data_Instance_Initialized{
    struct Sensor_Instance * p_inst;
};

/* Data signal k_Sensor_Evt_Sig_Changed can generate. */
struct Sensor_Evt_Data_Timer_Up{
    enum Sensor_Id id;
    uint32_t    val;
};

/* Events (i.e. signal + signal's data if any) that can be generated. */
struct Sensor_Evt{
	enum Sensor_Evt_Sig sig;
	union Sensor_Evt_Data{
        struct Sensor_Evt_Data_Instance_Initialized    initd;
        struct Sensor_Evt_Data_Timer_Up                timup; 
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_SENSOR_EVT_H */
