/** ****************************************************************************
 * @brief Events generated by Idein module.
 *
 * The public events Idein module generates.
 */

#ifndef FKMG_IDEIN_EVT_H
#define FKMG_IDEIN_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "id.h"
#include "midi/evt.h"


/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum Idein_Evt_Sig{
    k_Idein_Evt_Sig_Beg,                        // Inclusive
    k_Idein_Evt_Sig_Min = k_Idein_Evt_Sig_Beg,    // Inclusive
    k_Idein_Evt_Sig_1st = k_Idein_Evt_Sig_Beg,    // Inclusive

    k_Idein_Evt_Sig_Instance_Initialized = k_Idein_Evt_Sig_Beg,
    #if CONFIG_FKMG_IDEIN_SHUTDOWN_ENABLED
    k_Idein_Evt_Sig_Instance_Deinitialized,
    #endif
    k_Idein_Evt_Sig_Step_Occurred,
    k_Idein_Evt_Sig_Pot_Value_Changed,
    k_Idein_Evt_Sig_Btn_Value_Changed,
    k_Idein_Evt_Sig_LED_Write_Ready,
    k_Idein_Evt_Sig_MIDI_Write_Ready,
    k_Idein_Evt_Sig_Clock_Event,
    k_Idein_Evt_Sig_End,                        // Exclusive
    k_Idein_Evt_Sig_Max = k_Idein_Evt_Sig_End - 1,// Inclusive
    k_Idein_Evt_Sig_Lst = k_Idein_Evt_Sig_End - 1,// Inclusive
    k_Idein_Evt_Sig_Cnt = k_Idein_Evt_Sig_End
                      - k_Idein_Evt_Sig_Beg,	  // Inclusive
	k_Idein_Evt_Sig_Ivd = k_Idein_Evt_Sig_End
};

/* Forward references to prevent include interdependent items getting declared
 * out-of-order. */
struct Idein_Instance;

/* Data signal k_Idein_Evt_Sig_Instance_Initialized can generate. */
struct Idein_Evt_Data_Instance_Initialized{
    struct Idein_Instance * p_inst;
};

/* Data signal k_Idein_Evt_Sig_Clock_Event can generate. */
struct Idein_Evt_Sig_Clock_Event{
    uint16_t note; 
};

/* Events (i.e. signal + signal's data if any) that can be generated. */
struct Idein_Evt{
	enum Idein_Evt_Sig sig;
	union Idein_Evt_Data{
        struct Idein_Evt_Data_Instance_Initialized  initd;
        struct Idein_Evt_Sig_Clock_Event            note;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_IDEIN_EVT_H */
