/** ****************************************************************************
 * @brief Internal state machine events generated by UI.
 */

#ifndef FKMG_UI_SM_EVT_H
#define FKMG_UI_SM_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "../id.h"
#include "../instance_cfg.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum UI_SM_Evt_Sig{
    k_UI_SM_Evt_Sig_Beg,                           // Inclusive
    k_UI_SM_Evt_Sig_Min = k_UI_SM_Evt_Sig_Beg,    // Inclusive
    k_UI_SM_Evt_Sig_1st = k_UI_SM_Evt_Sig_Beg,    // Inclusive

	k_UI_SM_Evt_Sig_Init_Instance = k_UI_SM_Evt_Sig_Beg,
    #if CONFIG_FKMG_UI_ALLOW_SHUTDOWN
	k_UI_SM_Evt_Sig_Deinit_Instance,
    #endif
    k_UI_SM_Evt_Sig_Read_Encoder,
	k_UI_SM_Evt_Sig_Sensor_Setup_Complete,

    k_UI_SM_Evt_Sig_End,                           // Exclusive
    k_UI_SM_Evt_Sig_Max = k_UI_SM_Evt_Sig_End - 1,// Inclusive
    k_UI_SM_Evt_Sig_Lst = k_UI_SM_Evt_Sig_End - 1,// Inclusive
    k_UI_SM_Evt_Sig_Cnt = k_UI_SM_Evt_Sig_End
                         - k_UI_SM_Evt_Sig_Beg,	// Inclusive
	k_UI_SM_Evt_Sig_Ivd = k_UI_SM_Evt_Sig_End
};

/* Data signal k_UI_SM_Evt_Sig_Init_Instance can generate. */
struct UI_SM_Evt_Sig_Init_Instance{
    struct UI_Instance_Cfg cfg;
};

/* Data signal k_UI_SM_Sig_XXX can generate. */
struct UI_SM_Evt_Sig_Convert{
    enum UI_Id id;
};

struct UI_SM_Evt_Sig_Force_Change{
    enum UI_Id id;
};

/* Data signal k_UI_SM_Evt_Sig_Sensor_Setup_Complete can generate*/
struct UI_SM_Evt_Sig_Sensor_Setup_Complete{
    bool pass;
};

/* Events (i.e. signal + signal's data if any) UI State Machine generates. */
struct UI_SM_Evt{
	enum UI_SM_Evt_Sig sig;
	union UI_SM_Evt_Data{
        struct UI_SM_Evt_Sig_Init_Instance  init_inst;
        struct UI_SM_Evt_Sig_Sensor_Setup_Complete pass; 
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_UI_SM_EVT_H */
