/** ****************************************************************************
 * @brief Events generated by UI module.
 *
 * The public events UI module generates.
 */

#ifndef FKMG_UI_EVT_H
#define FKMG_UI_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "id.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum UI_Evt_Sig{
    k_UI_Evt_Sig_Beg,                        // Inclusive
    k_UI_Evt_Sig_Min = k_UI_Evt_Sig_Beg,    // Inclusive
    k_UI_Evt_Sig_1st = k_UI_Evt_Sig_Beg,    // Inclusive

    k_UI_Evt_Sig_Instance_Initialized = k_UI_Evt_Sig_Beg,
    #if CONFIG_FKMG_UI_SHUTDOWN_ENABLED
    k_UI_Evt_Sig_Instance_Deinitialized,
    #endif
    k_UI_Evt_Sig_TimerUp,                    //
    k_UI_Evt_Sig_Write,                      // Write to UI
    k_UI_Evt_Sig_Button_Press,                       // Read from UI


    k_UI_Evt_Sig_End,                        // Exclusive
    k_UI_Evt_Sig_Max = k_UI_Evt_Sig_End - 1,// Inclusive
    k_UI_Evt_Sig_Lst = k_UI_Evt_Sig_End - 1,// Inclusive
    k_UI_Evt_Sig_Cnt = k_UI_Evt_Sig_End
                      - k_UI_Evt_Sig_Beg,	  // Inclusive
	k_UI_Evt_Sig_Ivd = k_UI_Evt_Sig_End
};

/* Forward references to prevent include interdependent items getting declared
 * out-of-order. */
struct UI_Instance;

/* Data signal k_UI_Evt_Sig_Instance_Initialized can generate. */
struct UI_Evt_Data_Instance_Initialized{
    struct UI_Instance * p_inst;
};

/* Data signal k_UI_Evt_Sig_Changed can generate. */
struct UI_Evt_Data_Timer_Up{
    enum UI_Id id;
    uint32_t    val;
};

/* Events (i.e. signal + signal's data if any) that can be generated. */
struct UI_Evt{
	enum UI_Evt_Sig sig;
	union UI_Evt_Data{
        struct UI_Evt_Data_Instance_Initialized    initd;
        struct UI_Evt_Data_Timer_Up                timup; 
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_UI_EVT_H */
